apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'dev'
      server: 'https://kubernetes.default.svc'
    - namespace: '!argocd'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - https://github.com/parthivrmenon/argocd-bootstrapped-apps